version: '3'
services:
  mysql:
    container_name: "db"
    image: mysql:8.0.23
    volumes:
      - ./DB/docker/db/data:/var/lib/mysql
      - ./DB/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
  be:
    container_name: "be"
    build:
      context: ./
      dockerfile: ./BE/docker/app/Dockerfile
    depends_on:
      - mysql
    environment:
      - ENV_MODE=dev
      - BE_PORT=$BE_PORT
      - API_KEY=$API_KEY
      - API_SECRET=$API_SECRET
      - PRODUCT_CODE=$PRODUCT_CODE
      - API_BASE_URL=$API_BASE_URL
    ports:
      - $BE_PORT:8000
    working_dir: /usr/src/app/BE
    volumes:
      - ./:/usr/src/app
    command: realize start --run
    tty: true
    stdin_open: true
  fe:
    container_name: "fe"
    build:
      context: ./
      dockerfile: ./FE/Dockerfile
    environment:
      API_BASE_URL: $API_BASE_URL
    command: ['/bin/bash', '-c', 'NUXT_HOST=0.0.0.0 yarn run dev']
    working_dir: /usr/src/app/FE
    volumes:
      - ./:/usr/src/app
    ports:
      - $FE_PORT:3000
    environment:
      - HOST=0.0.0.0
