settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: src
  path: src
  commands:
    build:
      status: true
      method: go build -o /go/bin/src
    run:
      status: true
      method: /go/bin/src
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
